version: '2'
services:
  backend:
    image: allhaker/votingapp_backend:latest
    environment:
      DATABASE_URL: postgres://votingapp:votingapp@db/votingapp
    links:
    - db:db
  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: votingapp
      POSTGRES_PASSWORD: votingapp
      POSTGRES_USER: votingapp
    volumes:
    - /opt/docker/votingapp_data:/var/lib/postgresql/data
    labels:
      io.rancher.scheduler.affinity:host_label: Database=true
  frontend:
    image: allhaker/votingapp_frontend:latest
