version: '2'
services:
  balancer:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  backend:
    image: allhaker/votingapp_backend:latest
    environment:
      DATABASE_URL: postgres://votingapp:votingapp@db/votingapp
    links:
    - db:db
    labels:
      io.rancher.scheduler.global: 'true'
  seed-db:
    image: allhaker/votingapp_backend:latest
    command: node db/seeds.js
    environment:
      DATABASE_URL: postgres://votingapp:votingapp@db/votingapp
    links:
    - db:db
    labels:
      io.rancher.container.start_once: 'true'
  frontend:
    image: allhaker/votingapp_frontend:latest
    labels:
      io.rancher.scheduler.global: 'true'
  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: votingapp
      POSTGRES_PASSWORD: votingapp
      POSTGRES_USER: votingapp
    volumes:
    - /opt/docker/votingapp_data:/var/lib/postgresql/data
    labels:
      io.rancher.scheduler.affinity:host_label: Database=true
